language: cpp
dist: bionic

env:
  - BUILD_TYPE=Release

addons:
  apt:
    update: false
    packages:
    - libgtest-dev
    - doxygen
    - graphviz

script:
- set -e
- cmake --DCMAKE_BUILD_TYPE=${BUILD_TYPE} .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
- cmake --build . --target html

deploy:
  - provider: bintray
    skip_cleanup: true
    file: bintray.json
    user: bergentroll
    edge: true
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    keep_history: false
    local_dir: html
    on:
      branch: master
